### ISSUE TITLE
Nyheter kommer ikke

### ISSUE THREAD

**Issue by slogan-15** [UKMNorge/UKMDesignWordpress#102]
Hvor: https://ukmdev.no/alle-nyheter/ og https://ukm.no/alle-nyheter/
Hva: Nyheter kommer ikke på ukmdev.no.
Hvorfor:

**Comment by kimduo** [comment]
https://ukm.no/alle-nyheter/ får opp alle nyheter. Så denne fungerer heldigvis! 😄
