### ISSUE TITLE
Forskjellig padding på div

### ISSUE THREAD

**Issue by slogan-15** [UKMNorge/UKMDesignWordpress#105]
Hvor: https://ukmdev.no/deatnu-tana-workshopiarrangorsystem/
Hva: Padding er ikke lik vertikalt. 
Hvorfor: Ser dårlig ut og teksten kan ut av hvit boksen.
Løsningsforslag: **Bruk dynamisk størrelse på div-en slik at boksen tilpasses seg på forskjellige tekst størrelser** 

<img width="1299" alt="Skjermbilde 2021-10-07 kl  16 43 27" src="https://user-images.githubusercontent.com/10181004/136408464-118245ac-1c23-494d-9ec9-de7e5e8ea538.png">

<img width="924" alt="Skjermbilde 2021-10-07 kl  16 47 24" src="https://user-images.githubusercontent.com/10181004/136408696-2fe53a15-2da6-4d5d-80f6-792fca1e6aae.png">

**Comment by kimduo** [comment]
Denne løses sammen med #80
