### ISSUE TITLE
Whitespace når det ikke finnes bilde på header

### ISSUE THREAD

**Issue by slogan-15** [UKMNorge/UKMDesignWordpress#132]
Hvor: https://ukm.no/sandnes-ukmsandnes/
Hva: Det er whitespace på header når bilde finnes ikke.
Løsningsforslag: Bilde bruker `min-height` men når det ikke er bilde så min-height må ikke brukes.

<img width="1186" alt="Skjermbilde 2021-10-22 kl  12 50 27" src="https://user-images.githubusercontent.com/10181004/138442376-4f97d0ab-1093-4627-8047-849acf98b04b.png">

**Comment by kimduo** [comment]
Det ser ut som UKM Sandnes har lagt til et ugyldig bilde og derfor kommer det whitespace.
Andre arrangement uten forsidebilde skal ikke få det den whitespacen. 
<img width="1326" alt="Skjermbilde 2021-11-03 kl  09 17 24" src="https://user-images.githubusercontent.com/16731586/140028010-fae1324b-8098-4d63-886b-1e81e3ca5cc0.png">
<img width="1326" alt="Skjermbilde 2021-11-03 kl  09 17 44" src="https://user-images.githubusercontent.com/16731586/140028015-3b9dc197-8ee6-458b-b494-882182ac0638.png">
<img width="1334" alt="Skjermbilde 2021-11-03 kl  09 18 57" src="https://user-images.githubusercontent.com/16731586/140028016-7c3d448f-c8d1-4c0d-a050-42cda2d49bc7.png">
