### ISSUE TITLE
Video on top må vise absolutt hele filmen

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMDesignWordpress#17]
Nå kan man miste menybaren på filmene avhengig av skjermstørrelse

**Comment by mariusmandal** [comment]
Gjelder for video on top

**Comment by AsgeirSH** [comment]
Video on top fungerer ikke med blokker i Wordpress

**Comment by mariusmandal** [comment]
Tatt inn i feature req sys
