### ISSUE TITLE
Fylkes/lokalside med mange tidligere arrangement må være bedre

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMDesignWordpress#28]
For nå dytter den nyheter langt ned (se f.eks. ukm.no/viken) (tidligere relatert #27)

**Comment by mariusmandal** [comment]
Hvis mer enn 3, vis kun de tre siste, sammen med en "vis mer"-knapp. 
Ved trykk på knappen kan listen bare utvides nedover (jQuery-løsning)

**Comment by kimduo** [comment]
🤭
