### ISSUE TITLE
Logo størrelse på mobil

### ISSUE THREAD

**Issue by slogan-15** [UKMNorge/UKMDesignWordpress#76]
Hvor: https://ukmdev.no/
Hva: Logo størrelse på mobil skal ha dynamisk størrelse (f.eks. max-width, min-width). Det skal være større enn det er nå.
Hvorfor: Logo er for liten i forhold til innhold i nettsiden.

<img width="977" alt="Skjermbilde 2021-10-06 kl  11 25 55" src="https://user-images.githubusercontent.com/10181004/136177397-738a632c-8cc1-4dbe-ae06-64c5a1578876.png">

**Comment by kimduo** [comment]
**Selve commiten:**
#https://github.com/UKMNorge/UKMDesignAssets/commit/c7dbaa196878b548bc964f1a497f026012c3f299

**Hvordan den ser ut nå:**
![Skjermbilde 2021-10-06 kl  13 44 49](https://user-images.githubusercontent.com/16731586/136196254-c2195ccc-3089-43be-bacc-e42b99a77748.png)
