### ISSUE TITLE
Ikoner størrelse på footer på mobil

### ISSUE THREAD

**Issue by slogan-15** [UKMNorge/UKMDesignWordpress#77]
Hvor: https://ukmdev.no/
Hva: Ikoner (knapper) på footer på mobil for lite. Smart å bruke dynamisk størrelse.
Hvorfor: Vanskelig å se og trykke fra mobil pga størrelse.

<img width="981" alt="Skjermbilde 2021-10-06 kl  11 34 10" src="https://user-images.githubusercontent.com/10181004/136178427-db539d3c-38b5-431b-a09c-a3ee4485fef7.png">

**Comment by kimduo** [comment]
Kodelinjer som er endret (og deres commit-melding):
- SCSS: https://github.com/UKMNorge/UKMDesignAssets/commit/13156bf14a50b56a261533f6b367f131e1241ebe
- Layout: https://github.com/UKMNorge/UKMDesign/commit/a642982091664af306b9411fba9f7c0d5f6b2139

Hvordan det ser ut
![Skjermbilde 2021-10-06 kl  15 22 07](https://user-images.githubusercontent.com/16731586/136210632-d540e6e3-171d-4aa8-a500-3db47acad3b7.png)
:

**Comment by kimduo** [comment]
Kan vurderes å gjøre det enda større 😄 👍
