### ISSUE TITLE
Knapp større enn søkefeltet

### ISSUE THREAD

**Issue by slogan-15** [UKMNorge/UKMDesignWordpress#91]
Hvor: https://ukmdev.no/tromsogfinnmark/
Hva: Knappen er større enn søkefeltet.
Hvorfor: De skal ha samme høyde så lenge de representerer samme funskjonalitet.
NOTAT: Fungerer ikke på skjerm større > 991px.

<img width="1190" alt="Skjermbilde 2021-10-06 kl  16 18 43" src="https://user-images.githubusercontent.com/10181004/136222174-ed6fde9a-0435-45ff-a80d-4a3418cbbe14.png">

**Comment by kimduo** [comment]
Commit: https://github.com/UKMNorge/UKMDesignAssets/commit/a98cf9005c4744db1782e4d8b7434e7ebe823336
![Skjermbilde 2021-10-07 kl  14 15 24](https://user-images.githubusercontent.com/16731586/136382070-f112327a-a1ac-48f3-888c-71447a40b259.png)
